#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 31 14:07:23 2020

@author: roncavallo
"""

This tool is a command line tool to be used with Python 2.7 or Python 3.7

For Python 2.7 environments you will use file JAviaAPI1.py.
For Python 3.7 environments you will use file JAviaAPI2-Py3-7-6.py


This script is run at the command line and prompts to the user for what information they want to collect from any instance running API


How to use:
    
    - Download the JAviaAPI1.py file (Py 2.7) or JAviaAPI2-Py3-7-6.py (Py 3.7)  and the README to a directory on your machine
    - CREATE a blank file called creds.py 
    
        - Create a token in the instance by logging in and clicking API Token under your your user profile
        - Paste the following into the blank creds.py file:
            
#!/usr/bin/env python2
# -*- coding: utf-8 -*-


jatoken = "your token here"
username = "apitoken" ## leave this as-is. The username is always apitoken when using a token
    
    
## stop paste.
    
    - Load in Python 2.7 or 3.7 environments respectively
    - Open a terminal / command line and change directory to the files you downloaded
    - type "python JAviaAPI1.py" or "python JAviaAPI2-Py3-7-6.py" no quotes silly
    - Answer the prompts
    - Enjoy


More to come! Any collaborators welcome.

-RC.


